### PR TITLE
added eagledoc integration

### PR DESCRIPTION
**Pull request by p-stm**
I have added Eagle Doc (https://www.eagle-doc.com/) Invoice and Receipt OCR to the API list

### CODE REVIEW

**Comment by coscialp** [comment]
Hello, I'm sorry, invoice and receipt are deprecated, they must now be integrated into financial_parser.

**Comment by p-stm** [comment]
I have updated the integration with a financial_parser. Shall I delete the obsolete invoice and receipt parser?

**Comment by KyrianC** [comment]
Sorry for the long delay! Just need small fixes but otherwise looks good!

**Comment by p-stm** [comment]
We've identified a need to update the data mapping. Should I go ahead and update the pull request?

**Review by KyrianC — CHANGES_REQUESTED** [review]

**Review by KyrianC — APPROVED** [review]

**Pull request merged**
