### PR TITLE
Added Senseloaf Resume Parser Provider

### PR DESCRIPTION
**Pull request by Rutvik-Trivedi**
Added Senseloaf Resume Parser Provider. 

To Use, add your credentials to settings file and run
```python
from edenai_apis.apis.senseloaf.senseloaf_api import SenseloafApi
api = SenseloafApi()
result = api.ocr__resume_parser(file='path_to_file')
```

### CODE REVIEW

**Comment by DninoAdnane** [comment]
Hello @Rutvik-Trivedi , 

Thank you for your Pull request,

In order to review and merge your pull request quickly, can you please pull a more recent version of our code, and than update your pull request ? It will solve some conflicts and make it easier for us to review your code.

**Comment by Rutvik-Trivedi** [comment]
Hi @DninoAdnane , have updated the request

**Comment by DninoAdnane** [comment]
Thank you @Rutvik-Trivedi for you quick update, we will have a look at it and hopefully merge it as soon as possible

**Comment by Rutvik-Trivedi** [comment]
@coscialp Have created a fresh pull request #69 . Let me know if any problems are faced

**Pull request closed without merging**
